#-----abs-----
print('abs()')
print(abs(-7.3))
print(abs(-.5))
print(abs(-876.))
print(abs(-23))
print(abs(707))
#-----ord-----
print('ord()')
print(ord('Л'))
print(ord('6'))
print(ord('W'))
print(ord('&'))
#-----pow-----
print('pow()')
print(pow(4, 3))
print(pow(5, -2))
print(pow(-6, -2))
print(pow(1.25, -4))
print(pow(2.3, 5))
print(pow(4, 3, 3))
#-----str-----
print('str()')
print(str('Good morning!'))
print(str('123' * 5))
#-----help-----
print('help()')
help(pow)
help(abs)
#-----ascii-----
print('ascii()')
print(ascii('Конь'))
print(ascii('summer-лето'))
#-----bin-----
print('bin()')
print(bin(50))
print(bin(-50))
print(bin(123))
#-----bool-----
print('bool()')
print(bool(25))
print(bool())
print(bool(0))
print(bool(5) + 1)
#-----int-----
print('int()')
print(int(45.68))
print(int(-32.79))
print(int('789'))
print(int(float('145.78')))
print(int(0x25))
print(int(0o34))
print(int(0b1101))
#-----float-----
print('float()')
print(float('234.45'))
print(float(78))
#-----print-----
print('print()')
print('It is June now', end='! ')
print('Do you like \'Python?\'', 'Yes, I do', sep=' - ', end='!\n')
#-----format-----
print('format()')
print('{:07d}'.format(12))
print('My name is {:>10s}.'.format('Yuliia'))
print('I {verb} I can {ability:^8s}.'.format(ability='fly', verb='belive'))
print('{:10.1f}'.format(15.88))
#-----chr-----
print('chr()')
print(chr(13576))
print(chr(295))
print(chr(753))
#-----complex-----
print('complex()')
print(complex(7, 4.5))
print(complex(23, -1))
print(complex(831))
#-----round-----
print('round()')
print(round(2.95))
print(round(12.344, 2))
print(round(64.35, 1))
print(round(75.45, 1))
print(round(123.765, 2))